config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  resources :messages do
    resources :comments
  end

  root 'messages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :message

end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :user

  has_many :comments, :dependent => :destroy

  def last_comment_summary
    self.comments.last.try(:content).try(:truncate, 20)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :messages
  has_many :comments

  def display_name
    self.email.split("@").first
  end

  def posts_count
    # TODO: 請完成我
  end

  def words_count
    count = 0
    self.messages.find_each do |x|
      count += x.title.split(" ").size if x.title
      count += x.content.split(" ").size if x.content
    end

    self.comments.find_each do |x|
      count += x.content.split(" ").size if x.content
    end

    return count
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :set_message
  before_action :authenticate_user!

  def create
    @comment = @message.comments.build( comment_params )
    @comment.user = current_user

    @comment.save!

    redirect_to :back
  end

  def destroy
    @comment = current_user.comments.find( params[:id] )
    @comment.destroy

    redirect_to :back
  end

  protected

  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_message
    @message = Message.find( params[:message_id] )
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action :authenticate_user!, :except => [:index, :show]

  def index
    # TODO: fix N+1 queries for user and comments
    @messages = Message.order("id DESC").page( params[:page] )

    if params[:status] == "pending"
      # TODO: @messages = @messages.pending
      @messages = @messages.where( :status => "pending" )
    elsif params[:status] == "completed"
      # TODO: @messages = @messages.completed
      @messages = @messages.where( :status => "completed" )
    end

    if params[:days]
      # TODO: @messages = @messages.within_days(params[:days].to_i)
      @messages = @messages.where( ["created_at >= ?", Time.now - params[:days].to_i.days ] )
    end
  end

  def show
    @message = Message.find( params[:id] )
    @comment = Comment.new
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new( message_params )
    @message.user = current_user

    @message.save!

    redirect_to root_path
  end

  def edit
    @message = current_user.messages.find( params[:id] )

    render "new"
  end

  def update
    @message = current_user.messages.find( params[:id] )

    @message.update!( message_params )

    redirect_to message_path(@message)
  end

  def destroy
    @message = current_user.messages.find( params[:id] )
    @message.destroy

    redirect_to root_path
  end

  protected

  def message_params
    params.require(:message).permit(:title, :content, :category_name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HelpExercise</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1><%= link_to "Help Exercise", root_path %></h1>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<p>
      <% if current_user %>
          <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
          <%= link_to('修改密碼', edit_registration_path(:user)) %>
      <% else %>
          <%= link_to('註冊', new_registration_path(:user)) %> |
          <%= link_to('登入', new_session_path(:user)) %>
      <% end %>
</p>

<%= yield %>

</body>
</html>

app/views/messages/index.html.erb
<h2>Message list</h2>

<p>
<%= link_to "New Message", new_message_path %>
</p>

<p>
  <%= link_to "列出進行中訊息", messages_path( :status => "pending" ) %> |
  <%= link_to "列出一週內進行中的訊息", messages_path( :status => "pending", :days => 7 ) %> |
  <%= link_to "列出所有已完成訊息", messages_path( :status => "completed" ) %>
</p>

<%= paginate @messages %>

<table>
<tr>
  <th>標題</th>
  <th>狀態</th>
  <th>分類</th>
  <th>貼文使用者</th>
  <th>貼文時間</th>
  <th>最後一筆留言摘要</th>
  <th></th>
</tr>

<% @messages.each do |msg| %>
  <tr>
    <td><%= link_to msg.title, message_path(msg) %></td>
    <td><%= msg.status %></td>
    <td><%= msg.category_name %></td>
    <td><%= msg.user.display_name %></td>
    <td><%= msg.created_at.to_s(:short) %></td>
    <td><%= msg.last_comment_summary %></td>
    <td>
      <% if msg.user == current_user %>
        <%= link_to "Edit", edit_message_path(msg) %>
        <%= link_to "Delete", message_path(msg), :method => :delete, :data => { :confirm => "Are u sure?"} %>
      <% end %>
    </td>
  </tr>
<% end %>
</table>

<%= paginate @messages %>

app/views/messages/new.html.erb
<%= form_for @message do |f| %>

  <p>
    <%= f.label :title %>
    <%= f.text_field :title, :required => true %>
  </p>

  <p>
    <%= f.label :status %>
    <%= f.select :status, [ [ "進行中", "pending"], ["已解決", "completed"] ], :required => true %>
  </p>

  <p>
    <%= f.label :category_name %>
    <%= f.select :category_name, ["快報", "求物資", "求救"], :required => true %>
  </p>

  <p>
    <%= f.label :content %>
    <%= f.text_area :content, :required => true %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/messages/show.html.erb
<h2><%= @message.title %></h2>

<%= simple_format @message.content %>

<h2>Comments list</h2>

<%= form_for [@message, @comment] do |f| %>

  <p>
    <%= f.label :content %>
    <%= f.text_area :content, :required => true %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<% @message.comments.each do |comment| %>

  <p><%= simple_format comment.content %> at <%= comment.created_at.to_s(:short) %> by <%= comment.user.display_name %>

    <% if comment.user == current_user %>
      <%# TODO: 修改成 AJAX 版本的刪除 %>
      <%= link_to "Delete", message_comment_path(@message, comment), :method => :delete, :data => { :confirm => "Are u sure?"} %>
    <% end %>
  </p>

<% end %>